#!/usr/bin/env node
/**
 * Rebuild `packages/locale-ru/lib/client.js` from the translated dictionaries.
 *
 * Reads `packages/locale-ru/i18n/ru/<namespace>.json`, checks every file
 * against its English source (identical key set, non-empty values, identical
 * placeholders), and writes the browser bundle the DSH client module system
 * serves. Run it after editing any translation.
 *
 * Usage: node tools/build-locale.mjs
 *
 * @module tools/build-locale
 */

import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const REPO = dirname(HERE)
const PACKAGE = join(REPO, 'packages', 'locale-ru')
const RU_DIR = join(PACKAGE, 'i18n', 'ru')
const EN_DIR = join(PACKAGE, 'i18n', 'en')
const OUT_FILE = join(PACKAGE, 'lib', 'client.js')

const PACKAGE_NAME = JSON.parse(readFileSync(join(PACKAGE, 'package.json'), 'utf8')).name
const LOCALE_ID = 'ru'
const LOCALE_LABEL = 'Русский'
const FALLBACK = 'en'

/** Placeholder shapes the DSH locale registry interpolates. */
const PLACEHOLDER = /\{\{?[A-Za-z0-9_]+\}?\}|%s|%\d\$s/gu

const problems = []
const dictionaries = {}
let totalKeys = 0

for (const name of readdirSync(RU_DIR).sort()) {
  if (!name.endsWith('.json')) continue
  const namespace = name.slice(0, -'.json'.length)
  const ru = JSON.parse(readFileSync(join(RU_DIR, name), 'utf8'))
  let en = null
  try {
    en = JSON.parse(readFileSync(join(EN_DIR, name), 'utf8'))
  } catch {
    problems.push(`${namespace}: no English source to compare against`)
  }
  if (en !== null) {
    const missing = Object.keys(en).filter((key) => !(key in ru))
    const extra = Object.keys(ru).filter((key) => !(key in en))
    if (missing.length > 0) problems.push(`${namespace}: missing keys ${missing.slice(0, 5).join(', ')}`)
    if (extra.length > 0) problems.push(`${namespace}: extra keys ${extra.slice(0, 5).join(', ')}`)
  }
  const entries = []
  for (const [key, value] of Object.entries(ru)) {
    // A whitespace-only value can be a legitimate translation (the Russian
    // digit-group separator is U+00A0), so only a truly empty string is wrong.
    if (typeof value !== 'string' || value === '') {
      problems.push(`${namespace}: empty translation for ${key}`)
      continue
    }
    const source = en?.[key]
    if (typeof source === 'string') {
      const expected = [...source.matchAll(PLACEHOLDER)].map((match) => match[0]).sort().join('|')
      const actual = [...value.matchAll(PLACEHOLDER)].map((match) => match[0]).sort().join('|')
      if (expected !== actual) {
        problems.push(`${namespace}: placeholder mismatch in ${key}: en[${expected}] ${LOCALE_ID}[${actual}]`)
      }
    }
    entries.push(`\t\t\t${JSON.stringify(key)}: ${JSON.stringify(value)},`)
    totalKeys += 1
  }
  dictionaries[namespace] = entries.join('\n')
}

if (problems.length > 0) {
  console.error(`REFUSING TO BUILD — ${String(problems.length)} problem(s):`)
  for (const problem of problems.slice(0, 40)) console.error(`  ! ${problem}`)
  process.exit(1)
}

const body = Object.entries(dictionaries)
  .map(([namespace, entries]) => `\t\t\t${JSON.stringify(namespace)}: {\n${entries}\n\t\t\t},`)
  .join('\n')

const bundle = `/**
 * \`${PACKAGE_NAME}\` — browser half. GENERATED by \`tools/build-locale.mjs\`;
 * edit \`i18n/${LOCALE_ID}/*.json\` and rebuild instead of editing this file.
 *
 * Registers the \`${LOCALE_ID}\` language and one dictionary per client
 * namespace, so the shipped English/Chinese GUI can run in ${LOCALE_LABEL}.
 * Lookup falls back per key: a namespace or key without a translation keeps
 * showing \`${FALLBACK}\`, so this pack degrades gracefully.
 */

window.__ModuleLoader__.load({
	id: ${JSON.stringify(PACKAGE_NAME)},
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
		Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });

		/** Translated dictionaries, keyed by locale namespace. */
		const DICTIONARIES = {
${body}
		};

		/** Required client services: the locale registry. */
		const inject = ["locale"];

		/**
	 * Register the language definition and every translated namespace.
	 * @param ctx - browser context carrying the \`locale\` service.
	 */
		function apply(ctx) {
			ctx.effect(() => ctx.locale.addLanguage({
				id: ${JSON.stringify(LOCALE_ID)},
				label: ${JSON.stringify(LOCALE_LABEL)},
				fallback: ${JSON.stringify(FALLBACK)}
			}), "locale-${LOCALE_ID}: language");
			for (const [namespace, dictionary] of Object.entries(DICTIONARIES)) {
				ctx.effect(() => ctx.locale.register(namespace, ${JSON.stringify(LOCALE_ID)}, dictionary), "locale-${LOCALE_ID}: " + namespace);
			}
		}

		exports.apply = apply;
		exports.inject = inject;
		return module.exports;
	}
});
`

writeFileSync(OUT_FILE, bundle, 'utf8')
console.log(`namespaces: ${String(Object.keys(dictionaries).length)}`)
console.log(`keys: ${String(totalKeys)}`)
console.log(`bundle: ${OUT_FILE} (${String(Math.round(statSync(OUT_FILE).size / 1024))} KiB)`)
